from __future__ import annotations

from datetime import datetime, timezone
from types import SimpleNamespace

from plume.services.explanation_payloads import build_explanation_payload


def _summary() -> SimpleNamespace:
    return SimpleNamespace(
        source_latitude=35.0,
        source_longitude=-120.0,
        grid_rows=2,
        grid_columns=3,
        projection="EPSG:4326",
        max_concentration=1.2,
        mean_concentration=0.4,
        affected_cells_above_threshold=4,
        affected_area_m2=100.0,
        affected_area_hectares=0.01,
        dominant_spread_direction="north-east",
        threshold_used=1e-5,
        note="Test note.",
    )


def _payload(runtime_mode=None) -> dict[str, object]:
    execution_metadata = {}
    if runtime_mode is not None:
        execution_metadata["runtime_mode"] = runtime_mode
    result = SimpleNamespace(
        forecast_id="forecast-1",
        issued_at=datetime(2026, 1, 2, 3, 4, 5, tzinfo=timezone.utc),
        model_name="convlstm_online",
        execution_metadata=execution_metadata,
    )
    explanation_result = SimpleNamespace(
        used_llm=False,
        summary=_summary(),
        explanation={"risk_level": "low", "summary": "Test explanation."},
    )
    return build_explanation_payload(result, explanation_result)


def test_runtime_note_active_convlstm_wording():
    payload = _payload({"mode": "active_convlstm"})

    assert payload["runtime_note"] == "Forecast generated by the active ConvLSTM model/runtime."


def test_runtime_note_fallback_caution_wording():
    payload = _payload({"mode": "fallback"})

    assert "fallback behavior" in payload["runtime_note"]
    assert "extra caution" in payload["runtime_note"]


def test_runtime_note_dataset_window_mentions_not_live_sensor_input():
    payload = _payload({"mode": "dataset_window"})

    assert "dataset input window" in payload["runtime_note"]
    assert "not live sensor input" in payload["runtime_note"]


def test_runtime_note_demo_backend_not_operational_evidence():
    payload = _payload({"mode": "demo_backend"})

    assert "demo/mock backend" in payload["runtime_note"]
    assert "not operational evidence" in payload["runtime_note"]


def test_runtime_note_temporary_substitution_not_full_convlstm_runtime():
    payload = _payload({"mode": "temporary_substitution"})

    assert "temporary substitute model/backend" in payload["runtime_note"]
    assert "not be presented as full ConvLSTM runtime" in payload["runtime_note"]


def test_runtime_note_missing_runtime_mode_unknown_unavailable_wording():
    payload = _payload()

    assert payload["runtime_note"] == "Runtime mode is unknown or unavailable."


def test_existing_explanation_payload_fields_are_still_present():
    payload = _payload({"mode": "active_convlstm"})

    assert payload["forecast_id"] == "forecast-1"
    assert payload["issued_at"] == "2026-01-02T03:04:05+00:00"
    assert payload["model"] == "convlstm_online"
    assert payload["used_llm"] is False
    assert payload["summary"] == {
        "source_latitude": 35.0,
        "source_longitude": -120.0,
        "grid_rows": 2,
        "grid_columns": 3,
        "projection": "EPSG:4326",
        "max_concentration": 1.2,
        "mean_concentration": 0.4,
        "affected_cells_above_threshold": 4,
        "affected_area_m2": 100.0,
        "affected_area_hectares": 0.01,
        "dominant_spread_direction": "north-east",
        "threshold_used": 1e-5,
        "note": "Test note.",
    }
    assert payload["explanation"] == {"risk_level": "low", "summary": "Test explanation."}
