import { useMemo, useState } from "react";
import { opsClient } from "../api/opsClient";
import { useOpsJobs } from "../hooks/useOpsJobs";
import { useOpsStatus } from "../hooks/useOpsStatus";
import { useRetrainingRecommendation } from "../hooks/useRetrainingRecommendation";
import { useModelCandidateContext } from "../hooks/useModelCandidateContext";
import type { OpsJobRecord, RetrainingTriggerRequest } from "../types/ops.types";

function isJobActive(status: string | undefined): boolean { return status === "queued" || status === "running"; }
function formatTime(value: unknown): string { return typeof value === "string" && value.trim() ? value : "Not reported"; }

export function OpsTrainingTab() { const jobsState = useOpsJobs(); const statusState = useOpsStatus(); const recommendationState = useRetrainingRecommendation(); const candidateState = useModelCandidateContext();
const [manualOpen,setManualOpen]=useState(false); const [manualSubmitting,setManualSubmitting]=useState(false); const [manualNotice,setManualNotice]=useState<string|null>(null);
const jobs=jobsState.jobs?.jobs??[]; const runningJobs=jobs.filter((j)=>isJobActive(j.status)); const readiness=statusState.status?.retraining_readiness??{}; const shouldRetrain=recommendationState.recommendation?.should_retrain; const evidence=recommendationState.recommendation?.evidence??{};
const currentState=useMemo(()=>{ if(statusState.loading||recommendationState.loading||jobsState.loading)return "Checking status"; if(runningJobs.some((j)=>j.status==="running")) return "Training running"; if(runningJobs.some((j)=>j.status==="queued")) return "Training queued"; return shouldRetrain?"Ready to train":"Waiting for eligibility";},[statusState.loading,recommendationState.loading,jobsState.loading,runningJobs,shouldRetrain]);
async function refreshAll(){await Promise.all([jobsState.refresh(),statusState.refresh(),recommendationState.refresh(),candidateState.refresh()]);}
async function handleManualStart(payload: RetrainingTriggerRequest){setManualSubmitting(true);setManualNotice(null);try{const r=await opsClient.triggerRetraining(payload);setManualNotice(r.submitted?"Manual training job submitted.":"Submission was not accepted by backend policy.");setManualOpen(false);await refreshAll();}catch(e){setManualNotice(e instanceof Error?e.message:"Unable to submit manual training job.");}finally{setManualSubmitting(false);}}
return <div style={{display:"grid",gap:12}}><section className="panel"><h3>Automatic Training Status</h3><p className="muted">Automatic training remains the default workflow.</p><div className="button-row"><button className="secondary-button" onClick={()=>void refreshAll()} disabled={manualSubmitting}>Refresh training status</button></div><dl className="detail-list"><div className="detail-list-row"><dt>Current state</dt><dd>{currentState}</dd></div><div className="detail-list-row"><dt>Last training run</dt><dd>{formatTime(statusState.status?.latest_retraining_job?.completed_at)}</dd></div><div className="detail-list-row"><dt>Recommendation</dt><dd>{shouldRetrain===true?"Retrain":shouldRetrain===false?"Wait":"Not reported"}</dd></div></dl></section>
<section className="panel"><h3>Training Readiness Checklist</h3><ReadinessItem label="Enough new validated data" state={typeof evidence.new_samples==="number"?(shouldRetrain?"met":"not_met"):"unknown"} detail={typeof evidence.new_samples==="number"?`${evidence.new_samples} samples reported`:"Not reported"}/><ReadinessItem label="No retraining job currently running" state={runningJobs.length>0?"not_met":"met"} detail={runningJobs.length>0?`${runningJobs.length} queued/running job(s)`:"No queued/running jobs"}/><ReadinessItem label="Worker/resources available" state={typeof readiness.worker_available==="boolean"?(readiness.worker_available?"met":"not_met"):"unknown"} detail={typeof readiness.worker_available==="boolean"?"Resource signal reported":"Not reported"}/></section>
<section className="panel"><h3>Recent / Running Training Jobs</h3><JobList jobs={jobs} loading={jobsState.loading}/></section>
<section className="panel"><h3>Candidate Model Summary</h3><p className="muted">Review or activate model versions in Model Versions.</p><dl className="detail-list"><div className="detail-list-row"><dt>Current active model</dt><dd>{String(candidateState.context?.active_model?.model_id ?? statusState.status?.active_model?.model_id ?? "Not reported")}</dd></div></dl></section>
<section className="panel"><h3>Manual Training (Advanced Override)</h3><button className="secondary-button" onClick={()=>setManualOpen(true)}>Start manual training</button>{manualNotice?<p className="muted">{manualNotice}</p>:null}</section>
{manualOpen?<ManualTrainingModal onClose={()=>setManualOpen(false)} onSubmit={handleManualStart} submitting={manualSubmitting}/>:null}</div>; }

type ChecklistState="met"|"not_met"|"unknown";
function ReadinessItem({label,state,detail}:{label:string;state:ChecklistState;detail:string}){return <div className={`ops-readiness-item ops-readiness-${state}`}><span className="ops-readiness-dot"/><div><strong>{label}</strong><p className="muted" style={{margin:0}}>{detail}</p></div></div>;}
function JobList({jobs,loading}:{jobs:OpsJobRecord[];loading:boolean}){if(loading)return <p className="muted">Loading jobs…</p>; if(!jobs.length) return <p className="muted">No jobs yet.</p>; return <div style={{display:"grid",gap:8}}>{jobs.slice(0,5).map((job)=><article key={String(job.job_id)} className="ops-job-card"><strong>{String(job.job_id)} · {job.status??"unknown"}</strong><p className="muted">Created: {formatTime(job.created_at)} · Completed: {formatTime(job.completed_at)}</p></article>)}</div>;}
function ManualTrainingModal({ onClose, onSubmit, submitting }: { onClose: () => void; submitting: boolean; onSubmit: (payload: RetrainingTriggerRequest) => Promise<void> }) { const [datasetMode,setDatasetMode]=useState("buffered"); const [datasetValue,setDatasetValue]=useState(""); const [checkpointMode,setCheckpointMode]=useState("latest"); const [checkpointValue,setCheckpointValue]=useState(""); const [preset,setPreset]=useState("balanced"); const [maxEpochs,setMaxEpochs]=useState(8); const [maxRuntime,setMaxRuntime]=useState("30m"); const [advancedConfig,setAdvancedConfig]=useState("");
const runConfigRef=JSON.stringify({preset,max_epochs:maxEpochs,max_runtime:maxRuntime,checkpoint_mode:checkpointMode,checkpoint_ref:checkpointValue||undefined,advanced_config_json:advancedConfig||undefined}); const datasetSnapshotRef=datasetMode==="custom"?datasetValue:"buffered_internal_dataset";
return <div className="ops-modal-backdrop"><section className="panel ops-manual-modal"><h3>Start Manual Training</h3><p className="muted">Manual training bypasses normal automatic scheduling. Use it only when you know why.</p><div className="ops-modal-grid"><div className="field"><span>Dataset source</span><select value={datasetMode} onChange={(e)=>setDatasetMode(e.target.value)}><option value="buffered">Use buffered internal dataset</option><option value="custom">Custom dataset path/link</option></select></div><div className="field"><span>Base checkpoint</span><select value={checkpointMode} onChange={(e)=>setCheckpointMode(e.target.value)}><option value="latest">Latest best model</option><option value="active">Active production model</option><option value="custom">Custom checkpoint path</option></select></div>{datasetMode==="custom"?<div className="field"><span>Dataset path/link</span><input value={datasetValue} onChange={(e)=>setDatasetValue(e.target.value)} placeholder="/path/to/dataset · s3://bucket/dataset · https://..."/></div>:null}{checkpointMode==="custom"?<div className="field"><span>Checkpoint path</span><input value={checkpointValue} onChange={(e)=>setCheckpointValue(e.target.value)} placeholder="/path/to/checkpoint.pt · s3://bucket/model.pt"/></div>:null}<div className="field"><span>Training preset</span><select value={preset} onChange={(e)=>setPreset(e.target.value)}><option value="fast_refresh">Fast refresh</option><option value="balanced">Balanced</option><option value="high_accuracy">High accuracy</option><option value="recovery">Recovery / stabilization</option></select></div><div className="field"><span>Max runtime</span><select value={maxRuntime} onChange={(e)=>setMaxRuntime(e.target.value)}><option value="15m">15m</option><option value="30m">30m</option><option value="1h">1h</option><option value="2h">2h</option></select></div><div className="field" style={{gridColumn:"1 / -1"}}><span>Max epochs: {maxEpochs}</span><input type="range" min={1} max={40} step={1} value={maxEpochs} onChange={(e)=>setMaxEpochs(Number(e.target.value))}/></div></div><details><summary>Advanced options</summary><div className="field"><span>Custom config JSON</span><textarea rows={4} value={advancedConfig} onChange={(e)=>setAdvancedConfig(e.target.value)} placeholder="Optional. Not all fields may be wired by backend."/></div></details><p className="muted">Dataset/checkpoint/preset details are sent using run_config_ref and dataset_snapshot_ref. Backend support may be partial.</p><div className="button-row"><button className="secondary-button" onClick={onClose} disabled={submitting}>Cancel</button><button className="primary-button" onClick={()=>void onSubmit({manual_override:true,dataset_snapshot_ref:datasetSnapshotRef,run_config_ref:runConfigRef})} disabled={submitting}>{submitting?"Starting training...":"Start training"}</button></div></section></div>; }
