from __future__ import annotations

from typing import Protocol

from plume.services.forecast_service import ForecastRunResult


class ForecastRuntimeClient(Protocol):
    def run_batch_forecast(self, payload: dict | None) -> ForecastRunResult: ...

    def create_session(self, payload: dict | None) -> object: ...

    def list_sessions(self) -> list[object]: ...

    def get_session(self, session_id: str) -> object: ...

    def get_session_state(self, session_id: str) -> dict[str, object]: ...

    def ingest_observations(self, session_id: str, payload_dict: dict[str, object]) -> object: ...

    def update_session(self, session_id: str) -> object: ...

    def predict_session(self, session_id: str, payload: dict | None) -> ForecastRunResult: ...

    def get_latest_session_forecast_result(self, session_id: str) -> ForecastRunResult: ...
