service_registration_enabled: false
manager_api_url: ""
service_id: geospatial-plume-forecast
service_label: Geospatial Plume Forecast
service_version: "0.1.0"
service_icon: mdi-map-marker-radius
service_homepage_url: ""
service_global: false
service_heartbeat_seconds: 30
