from __future__ import annotations

from dataclasses import dataclass
import json

from plume.services.explanation_payloads import build_explanation_payload


@dataclass
class DecisionSupportResponse:
    payload: dict[str, object]


class DecisionSupportService:
    def __init__(self, runtime_client, explain_service, forecast_context_service=None):
        self.runtime_client = runtime_client
        self.explain_service = explain_service
        self.forecast_context_service = forecast_context_service

    def _answer_prediction_owner_from_provenance(self, context: dict) -> str | None:
        if not isinstance(context, dict):
            return None
        provenance = context.get("provenance", {}) if isinstance(context.get("provenance"), dict) else {}
        runtime = context.get("runtime", {}) if isinstance(context.get("runtime"), dict) else {}
        source = provenance.get("forecast_source") or runtime.get("forecast_source")
        family = provenance.get("model_family") or runtime.get("model_family") or "Unknown"
        model_id = provenance.get("model_id") or runtime.get("model_id")
        backend = provenance.get("model_backend") or runtime.get("model_backend") or runtime.get("backend")
        fallback = bool(provenance.get("fallback_used") or runtime.get("fallback_used"))
        if source == "dataset_playback":
            return "Predictions shown in the current context come from dataset playback/demo mode."
        if source == "active_model_inference" and family == "ConvLSTM":
            suffix = f" ({model_id})" if model_id else ""
            return f"Predictions are being generated by the active ConvLSTM model{suffix}."
        if fallback:
            return f"Predictions are being served by fallback logic using {family or backend or 'an unknown fallback backend'}, not active ConvLSTM inference."
        if source == "session_forecast":
            return f"Predictions come from the current session forecast backend ({family or backend or 'unknown'})."
        return None

    def _build_context_llm_prompt(self, context: dict) -> str:
        return (
            "You are an AI decision-support assistant for geospatial plume forecasts. "
            "Use only the provided forecast context. "
            "The first response should summarize current conditions and explain why the risk level is what it is. "
            "Do not mention raw grid cells or cell counts; translate model metrics into plain-language terms such as limited, moderate, broad, weak, stronger, or more widespread. "
            "Do not invent casualties, evacuation orders, exact weather, exact emergency instructions, or certainty. "
            "Do not claim live sensor confirmation unless observations_available=true appears in the context. "
            "Use provenance fields as the source of truth: never claim ConvLSTM is doing predictions unless forecast_source=active_model_inference and model_family=ConvLSTM; if forecast_source=dataset_playback, say it is demo/dataset playback and not active ConvLSTM inference. "
            "Return ONLY strict JSON with exactly these fields: "
            "summary, risk_level, recommendation, uncertainty_note."
        )

    def _truncate_string(self, value, max_len: int = 240) -> str | None:
        if value is None:
            return None
        text = str(value).strip()
        if not text:
            return None
        if len(text) <= max_len:
            return text
        return text[: max_len - 1].rstrip() + "…"

    def _limit_list(self, values, max_items: int = 6) -> list:
        if not isinstance(values, list):
            return []
        return values[:max_items]

    def _round_float(self, value, digits: int):
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return round(float(value), digits)
        return None

    def _build_compact_llm_context(self, context: dict) -> dict:
        if not isinstance(context, dict):
            return {}

        forecast = context.get("forecast", {}) if isinstance(context.get("forecast"), dict) else {}
        conditions = context.get("conditions", {}) if isinstance(context.get("conditions"), dict) else {}
        source = context.get("source", {}) if isinstance(context.get("source"), dict) else {}
        plume_metrics = context.get("plume_metrics", {}) if isinstance(context.get("plume_metrics"), dict) else {}
        runtime = context.get("runtime", {}) if isinstance(context.get("runtime"), dict) else {}
        raw = context.get("raw", {}) if isinstance(context.get("raw"), dict) else {}
        weather_context = context.get("weather_context", {}) if isinstance(context.get("weather_context"), dict) else {}
        provenance = context.get("provenance", {}) if isinstance(context.get("provenance"), dict) else {}
        model_inference = context.get("model_inference", {}) if isinstance(context.get("model_inference"), dict) else {}
        raw_model_inference = raw.get("model_inference", {}) if isinstance(raw.get("model_inference"), dict) else {}
        model_meta = model_inference or raw_model_inference

        compact = {
            "forecast": {
                "forecast_id": self._truncate_string(forecast.get("forecast_id")),
                "timestamp": self._truncate_string(forecast.get("timestamp")),
                "status": self._truncate_string(forecast.get("status")),
                "risk_level": self._truncate_string(forecast.get("risk_level")),
                "input_source": self._truncate_string(forecast.get("input_source")),
                "scenario_id": self._truncate_string(forecast.get("scenario_id")),
            },
            "model": {
                "name": self._truncate_string(model_meta.get("name") or model_meta.get("model_name")),
                "source": self._truncate_string(model_meta.get("source") or runtime.get("model_source")),
                "output_space": self._truncate_string(model_meta.get("output_space")),
                "prediction_engine": self._truncate_string(model_meta.get("prediction_engine") or runtime.get("prediction_engine") or provenance.get("inference_mode")),
                "forecast_source": self._truncate_string(provenance.get("forecast_source") or runtime.get("forecast_source")),
                "model_id": self._truncate_string(provenance.get("model_id") or runtime.get("model_id")),
                "model_family": self._truncate_string(provenance.get("model_family") or runtime.get("model_family")),
                "model_backend": self._truncate_string(provenance.get("model_backend") or runtime.get("model_backend")),
                "checkpoint_path": self._truncate_string(provenance.get("checkpoint_path") or runtime.get("checkpoint_path")),
                "fallback_used": bool(provenance.get("fallback_used") or runtime.get("fallback_used")),
                "dataset_playback_enabled": bool(provenance.get("dataset_playback_enabled") or runtime.get("dataset_playback_enabled")),
            },
            "source": {
                "latitude": self._round_float(source.get("latitude"), 5),
                "longitude": self._round_float(source.get("longitude"), 5),
                "pollutant": self._truncate_string(source.get("pollutant")),
                "emission_rate": self._round_float(source.get("emission_rate"), 2),
                "release_height_m": self._round_float(source.get("release_height_m"), 2),
                "duration_minutes": self._round_float(source.get("duration_minutes"), 2),
            },
            "weather": {
                "wind_speed_ms": self._round_float(conditions.get("wind_speed_ms"), 2),
                "wind_direction_label": self._truncate_string(conditions.get("wind_direction_label")),
                "wind_direction_deg": self._round_float(conditions.get("wind_direction_deg"), 1),
                "temperature_c": self._round_float(conditions.get("temperature_c"), 1),
                "humidity_pct": self._round_float(conditions.get("humidity_pct"), 1),
                "surface_pressure_hpa": self._round_float(conditions.get("surface_pressure_hpa"), 1),
                "pbl_height_m": self._round_float(conditions.get("pbl_height_m"), 1),
                "meteorology_source": self._truncate_string(conditions.get("meteorology_source") or weather_context.get("meteorology_source")),
                "meteorology_timestamp": self._truncate_string(conditions.get("meteorology_timestamp") or weather_context.get("meteorology_timestamp")),
            },
            "plume": {
                "max_score": self._round_float(plume_metrics.get("max_concentration"), 3),
                "mean_score": self._round_float(plume_metrics.get("mean_concentration"), 3),
                "threshold": self._round_float(plume_metrics.get("threshold_used"), 3),
                "plume_cell_count": plume_metrics.get("affected_cells_above_threshold"),
                "plume_fraction": self._round_float(plume_metrics.get("plume_fraction"), 3),
                "dominant_spread_direction": self._truncate_string(plume_metrics.get("dominant_spread_direction")),
                "affected_area_hectares": self._round_float(plume_metrics.get("affected_area_hectares"), 3),
                "grid_rows": plume_metrics.get("grid_rows"),
                "grid_columns": plume_metrics.get("grid_columns"),
            },
            "truthfulness": {
                "observations_available": bool(runtime.get("observations_available", False)),
                "live_sensor_confirmed": bool(runtime.get("live_sensor_confirmed", False)),
                "is_demo_dataset_playback": bool(forecast.get("input_source") == "dataset_playback" or provenance.get("forecast_source") == "dataset_playback" or runtime.get("forecast_source") == "dataset_playback"),
                "provenance_truth_rule": "ConvLSTM may be claimed only when forecast_source=active_model_inference and model_family=ConvLSTM.",
                "georeferencing_status": self._truncate_string(runtime.get("georeferencing_status")),
                "limitations": [self._truncate_string(item, max_len=120) for item in self._limit_list(context.get("limitations"), max_items=6) if self._truncate_string(item, max_len=120)],
            },
        }
        return compact



    def _is_usable_forecast_context(self, context: dict | None) -> tuple[bool, str]:
        if not isinstance(context, dict):
            return False, "missing_context"
        forecast = context.get("forecast", {}) if isinstance(context.get("forecast"), dict) else {}
        plume_metrics = context.get("plume_metrics", {}) if isinstance(context.get("plume_metrics"), dict) else {}
        conditions = context.get("conditions", {}) if isinstance(context.get("conditions"), dict) else {}
        source = context.get("source", {}) if isinstance(context.get("source"), dict) else {}

        def _usable_text(value, blocked: set[str]) -> bool:
            text = str(value or "").strip().lower()
            return bool(text) and text not in blocked

        if _usable_text(forecast.get("status"), {"unavailable", "forecast unavailable"}):
            return True, "forecast_status"
        if _usable_text(forecast.get("risk_level"), {"unknown", "unavailable"}):
            return True, "forecast_risk_level"
        if _usable_text(forecast.get("input_source"), {"unavailable"}):
            return True, "forecast_input_source"

        for metric_key in ("max_plume_score", "max_concentration"):
            metric = plume_metrics.get(metric_key)
            if isinstance(metric, (int, float)) and not isinstance(metric, bool):
                return True, f"plume_metrics.{metric_key}"

        wind_speed = conditions.get("wind_speed_ms")
        if isinstance(wind_speed, (int, float)) and not isinstance(wind_speed, bool):
            return True, "conditions.wind_speed_ms"
        latitude = source.get("latitude")
        longitude = source.get("longitude")
        if isinstance(latitude, (int, float)) and isinstance(longitude, (int, float)) and not isinstance(latitude, bool) and not isinstance(longitude, bool):
            return True, "source.coordinates"

        return False, "no_usable_fields"

    def _interpret_context_with_llm(self, context: dict) -> tuple[dict | None, bool, str | None]:
        llm_service = getattr(self.explain_service, "llm_service", None)
        if llm_service is None:
            print("[decision-support] no llm_service configured")
            return None, False, None

        try:
            try:
                compact_context = self._build_compact_llm_context(context)
            except Exception as compact_exc:
                print(f"[decision-support] failed to build compact LLM context: {compact_exc}")
                compact_context = {}
            compact_size = len(json.dumps(compact_context, separators=(",", ":"), ensure_ascii=False))
            print(f"[decision-support] compact LLM context size chars={compact_size} keys={list(compact_context.keys())}")
            llm_result = llm_service.interpret_context(
                system_prompt=self._build_context_llm_prompt(context),
                context=compact_context,
            )
        except Exception as exc:
            error = str(exc).strip() or exc.__class__.__name__
            print(f"[decision-support] LLM context interpretation failed with exception: {error}")
            return None, True, error

        if not llm_result.success:
            provider = getattr(llm_result, "provider", None) or getattr(getattr(llm_service, "llm_config", None), "provider", "unknown")
            model = getattr(llm_result, "model", None) or getattr(getattr(llm_service, "llm_config", None), "model", "unknown")
            error = getattr(llm_result, "error", None)
            raw_text = getattr(llm_result, "raw_text", None)
            short_error = str(error).strip() if error else "LLM interpretation returned unsuccessful result"
            print(
                "[decision-support] LLM context interpretation unsuccessful "
                f"provider={provider} model={model} error={short_error} raw_text={raw_text!r}"
            )
            return None, True, short_error

        print("[decision-support] LLM context interpretation succeeded")
        return {
            "summary": llm_result.summary or "Unavailable",
            "risk_level": llm_result.risk_level or "unknown",
            "recommendation": llm_result.recommendation or "Continue monitoring current forecast context.",
            "uncertainty_note": llm_result.uncertainty_note or "Grounded only in current forecast context.",
        }, True, None

    def latest(self, session_id: str | None = None) -> DecisionSupportResponse:
        if self.forecast_context_service is not None:
            context = self.forecast_context_service.latest(session_id=session_id, source="auto").payload
            context_ready, readiness_reason = self._is_usable_forecast_context(context if isinstance(context, dict) else None)
            if not context_ready:
                return DecisionSupportResponse(payload={
                    "mode": "context_loading",
                    "briefing": "Forecast context is still loading.",
                    "situation_summary": "Forecast context is still loading.",
                    "risk_level": "unknown",
                    "recommended_action": "Please wait a moment and try again.",
                    "uncertainty_limitations": "Grounded only in current forecast context.",
                    "forecast_evidence": context,
                    "system_honesty": "Context loading",
                    "follow_up_questions": [],
                    "used_context_fields": ["forecast_context.latest"],
                    "limitations": ["Context not ready"],
                    "live_inputs": context.get("runtime", {}) if isinstance(context, dict) else {},
                    "runtime_metadata": {"context_session_id": session_id, "used_llm": False, "context_ready": False, "readiness_reason": readiness_reason},
                })

            forecast = context.get("forecast", {}) if isinstance(context, dict) else {}
            plume_metrics = context.get("plume_metrics", {}) if isinstance(context, dict) else {}
            conditions = context.get("conditions", {}) if isinstance(context, dict) else {}
            risk = str(forecast.get("risk_level") or "unknown")
            status = str(forecast.get("status") or "forecast unavailable")
            wind = conditions.get("wind_direction_label") or conditions.get("wind_direction_deg") or "unknown"
            max_concentration = plume_metrics.get("max_concentration")
            has_plume = ("plume detected" in status.lower()) or (risk.lower() in {"medium", "high"}) or (
                isinstance(max_concentration, (int, float)) and max_concentration > 0
            )
            if has_plume:
                briefing = (
                    f"Plume is present with {risk} risk. Wind direction: {wind}. "
                    "Use precautionary controls based on current forecast context."
                )
            else:
                briefing = "No meaningful plume is currently indicated by the active forecast context."

            llm_explanation, llm_attempted, llm_error = self._interpret_context_with_llm(context if isinstance(context, dict) else {})
            if llm_explanation is not None:
                return DecisionSupportResponse(payload={
                    "mode": "llm",
                    "briefing": llm_explanation["summary"],
                    "situation_summary": llm_explanation["summary"],
                    "risk_level": llm_explanation["risk_level"],
                    "recommended_action": llm_explanation["recommendation"],
                    "uncertainty_limitations": llm_explanation["uncertainty_note"],
                    "forecast_evidence": context,
                    "system_honesty": "LLM-generated from current forecast context",
                    "follow_up_questions": [],
                    "used_context_fields": ["forecast_context.latest"],
                    "limitations": ["Grounded only in current forecast/session context"],
                    "live_inputs": context.get("runtime", {}) if isinstance(context, dict) else {},
                    "runtime_metadata": {"context_session_id": session_id, "used_llm": True, "llm_attempted": llm_attempted, "llm_error": llm_error},
                })

            return DecisionSupportResponse(payload={
                "mode": "context",
                "briefing": briefing,
                "situation_summary": briefing,
                "risk_level": risk,
                "recommended_action": "Continue monitoring current forecast context.",
                "uncertainty_limitations": "Grounded only in current forecast context.",
                "forecast_evidence": context,
                "system_honesty": "Context-derived decision support",
                "follow_up_questions": [],
                "used_context_fields": ["forecast_context.latest"],
                "limitations": ["Grounded only in current forecast/session context"],
                "live_inputs": context.get("runtime", {}) if isinstance(context, dict) else {},
                "runtime_metadata": {"context_session_id": session_id, "used_llm": False, "llm_attempted": llm_attempted, "llm_error": llm_error},
            })
        if session_id is None:
            sessions = self.runtime_client.list_sessions()
            if not sessions:
                return DecisionSupportResponse(payload={"mode": "stub", "briefing": "No active session.", "limitations": ["No sessions available"], "live_inputs": {"observation_count": 0}, "runtime_metadata": {}})
            session_id = sessions[-1].session_id
        result = self.runtime_client.get_latest_session_forecast_result(session_id)
        explanation_result = self.explain_service.explain(result, use_llm=True)
        explanation_payload = build_explanation_payload(result, explanation_result)
        detail = explanation_payload.get("explanation", {}) if isinstance(explanation_payload, dict) else {}
        return DecisionSupportResponse(payload={
            "mode": "llm" if explanation_payload.get("used_llm") else "stub",
            "briefing": detail.get("summary", "Unavailable"),
            "situation_summary": detail.get("summary", "Unavailable"),
            "risk_level": detail.get("risk_level", "unknown"),
            "recommended_action": detail.get("recommendation", "Unavailable"),
            "uncertainty_limitations": detail.get("uncertainty_note", "Unavailable"),
            "forecast_evidence": explanation_payload.get("summary", {}),
            "system_honesty": "LLM-generated" if explanation_payload.get("used_llm") else "Stub/development explanation",
            "follow_up_questions": [],
            "used_context_fields": ["forecast.summary", "session.state"],
            "limitations": ["Grounded only in current forecast/session context"],
            "live_inputs": self.runtime_client.get_session_state(session_id),
            "runtime_metadata": {"context_session_id": session_id, "used_llm": explanation_payload.get("used_llm")},
        })

    def chat(self, message: str, session_id: str | None = None) -> dict[str, object]:
        latest = self.latest(session_id=session_id).payload
        if latest.get("mode") == "context_loading":
            return {
                "mode": "context_loading",
                "answer": "Forecast context is still loading. Please wait a moment and try again.",
                "used_context_fields": latest.get("used_context_fields", []),
                "limitations": latest.get("limitations", []),
                "context_forecast_id": None,
                "context_session_id": latest.get("runtime_metadata", {}).get("context_session_id"),
                "runtime_metadata": {"used_llm": False},
            }
        context = latest.get("forecast_evidence")
        lower_message = str(message or "").lower()
        if isinstance(context, dict) and ("who" in lower_message and ("predict" in lower_message or "prediction" in lower_message)):
            owner_answer = self._answer_prediction_owner_from_provenance(context)
            if owner_answer:
                return {
                    "mode": latest.get("mode", "context"),
                    "answer": owner_answer,
                    "used_context_fields": [*latest.get("used_context_fields", []), "forecast_context.provenance"],
                    "limitations": latest.get("limitations", []),
                    "context_forecast_id": None,
                    "context_session_id": latest.get("runtime_metadata", {}).get("context_session_id"),
                    "runtime_metadata": {"used_llm": False, "answered_from_provenance": True},
                }
        llm_service = getattr(self.explain_service, "llm_service", None)

        if llm_service is not None and isinstance(context, dict):
            try:
                try:
                    compact_context = self._build_compact_llm_context(context)
                except Exception as compact_exc:
                    print(f"[decision-support] failed to build compact LLM context for chat: {compact_exc}")
                    compact_context = {}
                compact_size = len(json.dumps(compact_context, separators=(",", ":"), ensure_ascii=False))
                print(f"[decision-support] compact LLM context size chars={compact_size} keys={list(compact_context.keys())}")
                prompt = (
                    "You are an AI decision-support assistant for geospatial plume forecasts. "
                    "Answer the user's question using only the provided forecast context. "
                    "Use provenance fields as truth: never claim ConvLSTM is doing predictions unless forecast_source=active_model_inference and model_family=ConvLSTM; dataset_playback means demo/playback, not active ConvLSTM inference. "
                    "Do not mention raw grid cell counts; describe plume extent in plain language. "
                    "Be concise and honest about uncertainty."
                )
                result = llm_service.answer_context_question(
                    system_prompt=prompt,
                    context=compact_context,
                    question=message,
                )
                if result.get("success") and result.get("answer"):
                    return {
                        "mode": "llm",
                        "answer": result.get("answer"),
                        "used_context_fields": latest.get("used_context_fields", []),
                        "limitations": latest.get("limitations", []),
                        "context_forecast_id": None,
                        "context_session_id": latest.get("runtime_metadata", {}).get("context_session_id"),
                        "runtime_metadata": {"used_llm": True, "llm_error": None},
                    }
            except Exception as exc:
                print(f"[decision-support] LLM chat failed with exception: {exc}")
                pass

        briefing = str(latest.get("briefing", "")).strip()
        if not briefing or briefing.lower() == "unavailable":
            answer = "I do not have enough forecast context to answer that specific question right now."
        else:
            answer = briefing
        return {
            "mode": latest.get("mode", "stub"),
            "answer": answer,
            "used_context_fields": latest.get("used_context_fields", []),
            "limitations": latest.get("limitations", []),
            "context_forecast_id": None,
            "context_session_id": latest.get("runtime_metadata", {}).get("context_session_id"),
            "runtime_metadata": {"used_llm": False},
        }
