from __future__ import annotations

from typing import Any


_RUNTIME_NOTES = {
    "active_convlstm": "Forecast generated by the active ConvLSTM model/runtime.",
    "fallback": "Forecast used fallback behavior; treat results with extra caution.",
    "dataset_window": "Forecast used a dataset input window, not live sensor input.",
    "demo_backend": "Forecast came from a demo/mock backend and is not operational evidence.",
    "temporary_substitution": "Forecast used a temporary substitute model/backend and should not be presented as full ConvLSTM runtime.",
}


def _runtime_note_from_metadata(execution_metadata: dict[str, Any]) -> str:
    runtime_mode = execution_metadata.get("runtime_mode") if isinstance(execution_metadata, dict) else None
    mode = runtime_mode.get("mode") if isinstance(runtime_mode, dict) else None
    if isinstance(mode, str):
        note = _RUNTIME_NOTES.get(mode.strip().lower())
        if note:
            return note
    return "Runtime mode is unknown or unavailable."


def build_explanation_payload(result, explanation_result) -> dict[str, object]:
    return {
        "forecast_id": result.forecast_id,
        "issued_at": result.issued_at.isoformat(),
        "model": result.model_name,
        "used_llm": explanation_result.used_llm,
        "runtime_note": _runtime_note_from_metadata(getattr(result, "execution_metadata", {})),
        "summary": {
            "source_latitude": explanation_result.summary.source_latitude,
            "source_longitude": explanation_result.summary.source_longitude,
            "grid_rows": explanation_result.summary.grid_rows,
            "grid_columns": explanation_result.summary.grid_columns,
            "projection": explanation_result.summary.projection,
            "max_concentration": explanation_result.summary.max_concentration,
            "mean_concentration": explanation_result.summary.mean_concentration,
            "affected_cells_above_threshold": explanation_result.summary.affected_cells_above_threshold,
            "affected_area_m2": explanation_result.summary.affected_area_m2,
            "affected_area_hectares": explanation_result.summary.affected_area_hectares,
            "dominant_spread_direction": explanation_result.summary.dominant_spread_direction,
            "threshold_used": explanation_result.summary.threshold_used,
            "note": explanation_result.summary.note,
        },
        "explanation": explanation_result.explanation,
    }
